development:
  adapter: postgresql
  database: team18_dev
  host: localhost
  min_messages: warning
  username:

test:
  adapter: postgresql
  database: team18_test
  host: localhost
  min_messages: warning
  username: